import asyncio
from datetime import datetime, timedelta

from app.database import AsyncSessionLocal, Base, engine
from app.models import Match, Market, PackTier, Card

MATCHES = [
    {
        "sport": "NFL",
        "league": "NFL",
        "home_team": "Kansas City Chiefs",
        "away_team": "Buffalo Bills",
        "start_time": datetime.utcnow(),
        "is_live": True,
        "is_featured": True,
        "home_score": 14,
        "away_score": 10,
        "clock": "Q2 2:12",
        "periods": {
            "labels": ["Q1", "Q2", "Q3", "Q4"],
            "away": [7, 3, None, None],
            "home": [7, 7, None, None],
        },
        "markets": [
            ("moneyline", {"home": -145, "away": 125}),
            ("spread", {"home": {"line": -2.5, "odds": -110}, "away": {"line": 2.5, "odds": -110}}),
            ("total", {"line": 48.5, "over": -108, "under": -112}),
            ("alt_spread", {"home": {"line": -6.5, "odds": 240}, "away": {"line": 6.5, "odds": -310}}),
            ("alt_spread", {"home": {"line": 1.5, "odds": -340}, "away": {"line": -1.5, "odds": 260}}),
            ("alt_total", {"line": 44.5, "over": -150, "under": 125}),
            ("alt_total", {"line": 52.5, "over": 135, "under": -165}),
            (
                "player_prop",
                {"player": "Patrick Mahomes", "prop": "Passing Yards", "line": 275.5, "over": -115, "under": -105},
            ),
            (
                "player_prop",
                {"player": "Josh Allen", "prop": "Passing Yards", "line": 268.5, "over": -110, "under": -110},
            ),
            (
                "player_prop",
                {"player": "Travis Kelce", "prop": "Receiving Yards", "line": 65.5, "over": -120, "under": 100},
            ),
        ],
    },
    {
        "sport": "NFL",
        "league": "NFL",
        "home_team": "Philadelphia Eagles",
        "away_team": "Dallas Cowboys",
        "start_time": datetime.utcnow() + timedelta(days=1),
        "is_live": False,
        "is_featured": True,
        "home_score": 0,
        "away_score": 0,
        "markets": [
            ("moneyline", {"home": -155, "away": 135}),
            ("spread", {"home": {"line": -3.0, "odds": -110}, "away": {"line": 3.0, "odds": -110}}),
            ("total", {"line": 45.5, "over": -110, "under": -110}),
        ],
    },
    {
        "sport": "NFL",
        "league": "NFL",
        "home_team": "San Francisco 49ers",
        "away_team": "Seattle Seahawks",
        "start_time": datetime.utcnow() + timedelta(days=2),
        "is_live": False,
        "home_score": 0,
        "away_score": 0,
        "markets": [
            ("moneyline", {"home": -185, "away": 158}),
            ("spread", {"home": {"line": -4.5, "odds": -112}, "away": {"line": 4.5, "odds": -108}}),
            ("total", {"line": 43.5, "over": -115, "under": -105}),
        ],
    },
    {
        "sport": "NBA",
        "league": "NBA",
        "home_team": "Denver Nuggets",
        "away_team": "Golden State Warriors",
        "start_time": datetime.utcnow(),
        "is_live": True,
        "is_featured": True,
        "home_score": 58,
        "away_score": 61,
        "clock": "Q3 4:47",
        "periods": {
            "labels": ["Q1", "Q2", "Q3", "Q4"],
            "away": [30, 22, 9, None],
            "home": [28, 20, 10, None],
        },
        "markets": [
            ("moneyline", {"home": -130, "away": 110}),
            ("spread", {"home": {"line": -2.5, "odds": -110}, "away": {"line": 2.5, "odds": -110}}),
            ("total", {"line": 228.5, "over": -110, "under": -110}),
            (
                "player_prop",
                {"player": "Nikola Jokic", "prop": "Points", "line": 26.5, "over": -110, "under": -110},
            ),
            (
                "player_prop",
                {"player": "Stephen Curry", "prop": "3-Pointers Made", "line": 4.5, "over": -125, "under": 105},
            ),
        ],
    },
    {
        "sport": "NBA",
        "league": "NBA",
        "home_team": "Boston Celtics",
        "away_team": "Miami Heat",
        "start_time": datetime.utcnow() + timedelta(days=1),
        "is_live": False,
        "home_score": 0,
        "away_score": 0,
        "markets": [
            ("moneyline", {"home": -210, "away": 175}),
            ("spread", {"home": {"line": -5.5, "odds": -108}, "away": {"line": 5.5, "odds": -112}}),
            ("total", {"line": 219.5, "over": -110, "under": -110}),
        ],
    },
    {
        "sport": "MLB",
        "league": "MLB",
        "home_team": "Boston Red Sox",
        "away_team": "New York Yankees",
        "start_time": datetime.utcnow(),
        "is_live": True,
        "home_score": 3,
        "away_score": 4,
        "clock": "Bot 7th",
        "periods": {
            "labels": ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            "away": [1, 0, 0, 2, 0, 1, 0, None, None],
            "home": [0, 1, 0, 0, 2, 0, None, None, None],
        },
        "markets": [
            ("moneyline", {"home": 105, "away": -125}),
            ("spread", {"home": {"line": 1.5, "odds": -130}, "away": {"line": -1.5, "odds": 110}}),
            ("total", {"line": 8.5, "over": -105, "under": -115}),
            ("nrfi", {"yes": 105, "no": -130}),
            ("alt_total", {"line": 7.5, "over": -160, "under": 135}),
            (
                "player_prop",
                {"player": "Aaron Judge", "prop": "Total Bases", "line": 1.5, "over": -105, "under": -115},
            ),
            (
                "player_prop",
                {"player": "Gerrit Cole", "prop": "Strikeouts", "line": 6.5, "over": -120, "under": 100},
            ),
        ],
    },
    {
        "sport": "Soccer",
        "league": "Premier League",
        "home_team": "Arsenal",
        "away_team": "Manchester City",
        "start_time": datetime.utcnow(),
        "is_live": True,
        "is_featured": True,
        "home_score": 1,
        "away_score": 2,
        "clock": "67'",
        "periods": {
            "labels": ["1st Half", "2nd Half"],
            "away": [1, 1],
            "home": [0, 1],
        },
        "markets": [
            ("moneyline", {"home": 220, "away": -120}),
            ("spread", {"home": {"line": 0.5, "odds": -105}, "away": {"line": -0.5, "odds": -115}}),
            ("total", {"line": 2.5, "over": -120, "under": 100}),
        ],
    },
    {
        "sport": "Tennis",
        "league": "ATP",
        "home_team": "Novak Djokovic",
        "away_team": "Carlos Alcaraz",
        "start_time": datetime.utcnow(),
        "is_live": True,
        "home_score": 1,
        "away_score": 1,
        "clock": "Set 2 4-4",
        "periods": {
            "labels": ["Set 1", "Set 2", "Set 3"],
            "away": [4, 4, None],
            "home": [6, 4, None],
        },
        "markets": [
            ("moneyline", {"home": -135, "away": 115}),
            ("spread", {"home": {"line": -1.5, "odds": 145}, "away": {"line": 1.5, "odds": -175}}),
            ("total", {"line": 22.5, "over": -110, "under": -110}),
        ],
    },
    {
        "sport": "NHL",
        "league": "NHL",
        "home_team": "Boston Bruins",
        "away_team": "New York Rangers",
        "start_time": datetime.utcnow() + timedelta(hours=6),
        "is_live": False,
        "home_score": 0,
        "away_score": 0,
        "markets": [
            ("moneyline", {"home": -150, "away": 130}),
            ("spread", {"home": {"line": -1.5, "odds": 165}, "away": {"line": 1.5, "odds": -195}}),
            ("total", {"line": 6.0, "over": -105, "under": -115}),
        ],
    },
]


PACK_TIERS = [
    {
        "name": "Bronze Raw Card",
        "category": "Pokemon",
        "price": 20,
        "description": "Common & Uncommon raw cards. Great for new collectors.",
        "top_pull_text": "Eevee PSA 9 ~$45",
        "rarity_odds": {"Common": 60, "Uncommon": 30, "Rare": 10},
        "cards": [
            ("Meowth", "Base Set", "#052", 10, "Common", 13),
            ("Rattata", "Base Set", "#061", 9, "Common", 8),
            ("Eevee", "Base Set", "#051", 9, "Uncommon", 45),
            ("Vulpix", "Base Set", "#068", 9, "Uncommon", 22),
            ("Machoke", "Base Set", "#034", 9, "Rare", 65),
            ("Dratini", "Fossil", "#028", 9, "Rare", 90),
        ],
    },
    {
        "name": "Silver Raw Card",
        "category": "Pokemon",
        "price": 50,
        "description": "Uncommon & Rare guaranteed. Ultra Rare chance.",
        "top_pull_text": "Gyarados PSA 10 ~$320",
        "rarity_odds": {"Common": 20, "Uncommon": 40, "Rare": 30, "Ultra Rare": 10},
        "cards": [
            ("Pidgey", "Base Set", "#057", 9, "Common", 18),
            ("Caterpie", "Base Set", "#045", 9, "Common", 15),
            ("Growlithe", "Base Set", "#028", 9, "Uncommon", 40),
            ("Ponyta", "Base Set", "#060", 9, "Uncommon", 35),
            ("Alakazam", "Base Set", "#001", 9, "Rare", 266),
            ("Machamp", "Base Set", "#008", 9, "Rare", 180),
            ("Gyarados", "Base Set", "#006", 10, "Ultra Rare", 320),
            ("Dragonite", "Fossil", "#004", 9, "Ultra Rare", 300),
        ],
    },
    {
        "name": "Gold Raw Card",
        "category": "Pokemon",
        "price": 100,
        "description": "Rare & Ultra Rare raw cards. Secret Rare 15% chance.",
        "top_pull_text": "Charizard PSA 8 ~$1.2k",
        "rarity_odds": {"Uncommon": 10, "Rare": 40, "Ultra Rare": 35, "Secret Rare": 15},
        "cards": [
            ("Kadabra", "Base Set", "#032", 9, "Uncommon", 55),
            ("Magneton", "Base Set", "#009", 9, "Uncommon", 48),
            ("Snorlax", "Jungle", "#011", 9, "Rare", 210),
            ("Lapras", "Fossil", "#010", 9, "Rare", 190),
            ("Blastoise", "Base Set", "#002", 9, "Ultra Rare", 650),
            ("Venusaur", "Base Set", "#015", 9, "Ultra Rare", 600),
            ("Charizard", "Base Set", "#004", 8, "Secret Rare", 1200),
            ("Charizard", "Base Set", "#004", 9, "Secret Rare", 1300),
        ],
    },
    {
        "name": "Platinum Raw Card",
        "category": "Pokemon",
        "price": 500,
        "description": "Ultra Rare guaranteed. Trophy & promo raw cards possible.",
        "top_pull_text": "Trophy Pikachu PSA 9 ~$4.8k",
        "rarity_odds": {"Rare": 10, "Ultra Rare": 40, "Secret Rare": 35, "1st Edition": 15},
        "cards": [
            ("Mewtwo", "Base Set", "#010", 9, "Rare", 400),
            ("Gengar", "Fossil", "#005", 9, "Rare", 380),
            ("Charizard", "Base Set", "#004", 7, "Ultra Rare", 1800),
            ("Blastoise", "Base Set 1st Ed.", "#002", 8, "Ultra Rare", 2200),
            ("Trophy Pikachu", "Promo", "#TR1", 9, "Secret Rare", 4800),
            ("Master's Key Pikachu", "Promo", "#TR2", 9, "Secret Rare", 4500),
            ("Charizard", "Base Set 1st Ed.", "#004", 7, "1st Edition", 4900),
            ("Blastoise", "Base Set 1st Ed.", "#002", 9, "1st Edition", 5000),
        ],
    },
    {
        "name": "Diamond Raw Card",
        "category": "Pokemon",
        "price": 1000,
        "description": "Highest tier. 1st Edition pulls highly likely.",
        "top_pull_text": "Charizard 1st Ed PSA 10 ~$15k",
        "rarity_odds": {"Ultra Rare": 15, "Secret Rare": 45, "1st Edition": 40},
        "cards": [
            ("Charizard", "Base Set", "#004", 9, "Ultra Rare", 6000),
            ("Blastoise", "Base Set", "#002", 9, "Ultra Rare", 5500),
            ("Trophy Pikachu", "Promo", "#TR1", 10, "Secret Rare", 9000),
            ("Pikachu Illustrator", "Promo", "#IL1", 8, "Secret Rare", 8500),
            ("Charizard", "Base Set 1st Ed.", "#004", 9, "1st Edition", 12000),
            ("Charizard", "Base Set 1st Ed.", "#004", 10, "1st Edition", 15000),
        ],
    },
    {
        "category": "Basketball",
        "name": "Bronze Raw Card",
        "price": 20,
        "description": "Common & Uncommon raw cards. Great for new collectors.",
        "top_pull_text": "D. Sterling Rookie PSA 9 ~$45",
        "rarity_odds": {"Common": 60, "Uncommon": 30, "Rare": 10},
        "cards": [
            ("M. Wallace", "Hoops Draft", "#052", 10, "Common", 13),
            ("K. Reeves", "Hoops Draft", "#061", 9, "Common", 8),
            ("D. Sterling", "Hoops Draft", "#001", 9, "Uncommon", 45),
            ("T. Brantley", "Hoops Draft", "#068", 9, "Uncommon", 22),
            ("A. Voss", "Prestige Rookies", "#034", 9, "Rare", 65),
            ("L. Crawford", "Prestige Rookies", "#028", 9, "Rare", 90),
        ],
    },
    {
        "category": "Basketball",
        "name": "Silver Raw Card",
        "price": 50,
        "description": "Uncommon & Rare guaranteed. Ultra Rare chance.",
        "top_pull_text": "R. Holt PSA 10 ~$320",
        "rarity_odds": {"Common": 20, "Uncommon": 40, "Rare": 30, "Ultra Rare": 10},
        "cards": [
            ("J. Vance", "Hoops Draft", "#057", 9, "Common", 18),
            ("C. Banner", "Hoops Draft", "#045", 9, "Common", 15),
            ("S. Ortiz", "Prestige Rookies", "#028", 9, "Uncommon", 40),
            ("N. Drexler", "Prestige Rookies", "#060", 9, "Uncommon", 35),
            ("P. Sinclair", "Chrome Elite", "#001", 9, "Rare", 266),
            ("D. Sterling", "Chrome Elite", "#008", 9, "Rare", 180),
            ("R. Holt", "Chrome Elite", "#006", 10, "Ultra Rare", 320),
            ("A. Voss", "Prestige Rookies", "#004", 9, "Ultra Rare", 300),
        ],
    },
    {
        "category": "Basketball",
        "name": "Gold Raw Card",
        "price": 100,
        "description": "Rare & Ultra Rare raw cards. Secret Rare 15% chance.",
        "top_pull_text": "L. Crawford PSA 8 ~$1.2k",
        "rarity_odds": {"Uncommon": 10, "Rare": 40, "Ultra Rare": 35, "Secret Rare": 15},
        "cards": [
            ("K. Reeves", "Hoops Draft", "#032", 9, "Uncommon", 55),
            ("T. Brantley", "Hoops Draft", "#009", 9, "Uncommon", 48),
            ("M. Wallace", "Chrome Elite", "#011", 9, "Rare", 210),
            ("C. Banner", "Chrome Elite", "#010", 9, "Rare", 190),
            ("R. Holt", "Chrome Elite", "#002", 9, "Ultra Rare", 650),
            ("S. Ortiz", "Chrome Elite", "#015", 9, "Ultra Rare", 600),
            ("L. Crawford", "Chrome Elite", "#004", 8, "Secret Rare", 1200),
            ("L. Crawford", "Chrome Elite", "#004", 9, "Secret Rare", 1300),
        ],
    },
    {
        "category": "Basketball",
        "name": "Platinum Raw Card",
        "price": 500,
        "description": "Ultra Rare guaranteed. Trophy & promo raw cards possible.",
        "top_pull_text": "All-Star MVP PSA 9 ~$4.8k",
        "rarity_odds": {"Rare": 10, "Ultra Rare": 40, "Secret Rare": 35, "1st Edition": 15},
        "cards": [
            ("D. Sterling", "Hoops Draft", "#010", 9, "Rare", 400),
            ("A. Voss", "Prestige Rookies", "#005", 9, "Rare", 380),
            ("L. Crawford", "Chrome Elite", "#004", 7, "Ultra Rare", 1800),
            ("R. Holt", "Chrome Elite 1st Ed.", "#002", 8, "Ultra Rare", 2200),
            ("All-Star MVP", "Promo", "#TR1", 9, "Secret Rare", 4800),
            ("Finals MVP", "Promo", "#TR2", 9, "Secret Rare", 4500),
            ("L. Crawford", "Chrome Elite 1st Ed.", "#004", 7, "1st Edition", 4900),
            ("R. Holt", "Chrome Elite 1st Ed.", "#002", 9, "1st Edition", 5000),
        ],
    },
    {
        "category": "Basketball",
        "name": "Diamond Raw Card",
        "price": 1000,
        "description": "Highest tier. 1st Edition pulls highly likely.",
        "top_pull_text": "L. Crawford 1st Ed PSA 10 ~$15k",
        "rarity_odds": {"Ultra Rare": 15, "Secret Rare": 45, "1st Edition": 40},
        "cards": [
            ("L. Crawford", "Chrome Elite", "#004", 9, "Ultra Rare", 6000),
            ("R. Holt", "Chrome Elite", "#002", 9, "Ultra Rare", 5500),
            ("All-Star MVP", "Promo", "#TR1", 10, "Secret Rare", 9000),
            ("Slam Dunk Champion", "Promo", "#IL1", 8, "Secret Rare", 8500),
            ("L. Crawford", "Chrome Elite 1st Ed.", "#004", 9, "1st Edition", 12000),
            ("L. Crawford", "Chrome Elite 1st Ed.", "#004", 10, "1st Edition", 15000),
        ],
    },
    {
        "category": "Football",
        "name": "Bronze Raw Card",
        "price": 20,
        "description": "Common & Uncommon raw cards. Great for new collectors.",
        "top_pull_text": "K. Ironwood Rookie PSA 9 ~$45",
        "rarity_odds": {"Common": 60, "Uncommon": 30, "Rare": 10},
        "cards": [
            ("T. Brockman", "Gridiron Legends", "#052", 10, "Common", 13),
            ("R. Mayfair", "Gridiron Legends", "#061", 9, "Common", 8),
            ("K. Ironwood", "Gridiron Legends", "#001", 9, "Uncommon", 45),
            ("D. Lassiter", "Gridiron Legends", "#068", 9, "Uncommon", 22),
            ("M. Pierce", "Combine Prospects", "#034", 9, "Rare", 65),
            ("B. Sawyer", "Combine Prospects", "#028", 9, "Rare", 90),
        ],
    },
    {
        "category": "Football",
        "name": "Silver Raw Card",
        "price": 50,
        "description": "Uncommon & Rare guaranteed. Ultra Rare chance.",
        "top_pull_text": "C. Whitlock PSA 10 ~$320",
        "rarity_odds": {"Common": 20, "Uncommon": 40, "Rare": 30, "Ultra Rare": 10},
        "cards": [
            ("S. Donnelly", "Gridiron Legends", "#057", 9, "Common", 18),
            ("A. Tarpley", "Gridiron Legends", "#045", 9, "Common", 15),
            ("J. Castellan", "Combine Prospects", "#028", 9, "Uncommon", 40),
            ("M. Pierce", "Combine Prospects", "#060", 9, "Uncommon", 35),
            ("K. Ironwood", "Pro Bowl Chrome", "#001", 9, "Rare", 266),
            ("T. Brockman", "Pro Bowl Chrome", "#008", 9, "Rare", 180),
            ("C. Whitlock", "Pro Bowl Chrome", "#006", 10, "Ultra Rare", 320),
            ("B. Sawyer", "Combine Prospects", "#004", 9, "Ultra Rare", 300),
        ],
    },
    {
        "category": "Football",
        "name": "Gold Raw Card",
        "price": 100,
        "description": "Rare & Ultra Rare raw cards. Secret Rare 15% chance.",
        "top_pull_text": "D. Lassiter PSA 8 ~$1.2k",
        "rarity_odds": {"Uncommon": 10, "Rare": 40, "Ultra Rare": 35, "Secret Rare": 15},
        "cards": [
            ("R. Mayfair", "Gridiron Legends", "#032", 9, "Uncommon", 55),
            ("A. Tarpley", "Gridiron Legends", "#009", 9, "Uncommon", 48),
            ("T. Brockman", "Pro Bowl Chrome", "#011", 9, "Rare", 210),
            ("S. Donnelly", "Pro Bowl Chrome", "#010", 9, "Rare", 190),
            ("C. Whitlock", "Pro Bowl Chrome", "#002", 9, "Ultra Rare", 650),
            ("J. Castellan", "Pro Bowl Chrome", "#015", 9, "Ultra Rare", 600),
            ("D. Lassiter", "Pro Bowl Chrome", "#004", 8, "Secret Rare", 1200),
            ("D. Lassiter", "Pro Bowl Chrome", "#004", 9, "Secret Rare", 1300),
        ],
    },
    {
        "category": "Football",
        "name": "Platinum Raw Card",
        "price": 500,
        "description": "Ultra Rare guaranteed. Trophy & promo raw cards possible.",
        "top_pull_text": "Super Bowl MVP PSA 9 ~$4.8k",
        "rarity_odds": {"Rare": 10, "Ultra Rare": 40, "Secret Rare": 35, "1st Edition": 15},
        "cards": [
            ("K. Ironwood", "Gridiron Legends", "#010", 9, "Rare", 400),
            ("M. Pierce", "Combine Prospects", "#005", 9, "Rare", 380),
            ("D. Lassiter", "Pro Bowl Chrome", "#004", 7, "Ultra Rare", 1800),
            ("C. Whitlock", "Pro Bowl Chrome 1st Ed.", "#002", 8, "Ultra Rare", 2200),
            ("Super Bowl MVP", "Promo", "#TR1", 9, "Secret Rare", 4800),
            ("Pro Bowl MVP", "Promo", "#TR2", 9, "Secret Rare", 4500),
            ("D. Lassiter", "Pro Bowl Chrome 1st Ed.", "#004", 7, "1st Edition", 4900),
            ("C. Whitlock", "Pro Bowl Chrome 1st Ed.", "#002", 9, "1st Edition", 5000),
        ],
    },
    {
        "category": "Football",
        "name": "Diamond Raw Card",
        "price": 1000,
        "description": "Highest tier. 1st Edition pulls highly likely.",
        "top_pull_text": "D. Lassiter 1st Ed PSA 10 ~$15k",
        "rarity_odds": {"Ultra Rare": 15, "Secret Rare": 45, "1st Edition": 40},
        "cards": [
            ("D. Lassiter", "Pro Bowl Chrome", "#004", 9, "Ultra Rare", 6000),
            ("C. Whitlock", "Pro Bowl Chrome", "#002", 9, "Ultra Rare", 5500),
            ("Super Bowl MVP", "Promo", "#TR1", 10, "Secret Rare", 9000),
            ("Heisman Winner", "Promo", "#IL1", 8, "Secret Rare", 8500),
            ("D. Lassiter", "Pro Bowl Chrome 1st Ed.", "#004", 9, "1st Edition", 12000),
            ("D. Lassiter", "Pro Bowl Chrome 1st Ed.", "#004", 10, "1st Edition", 15000),
        ],
    },
    {
        "category": "Baseball",
        "name": "Bronze Raw Card",
        "price": 20,
        "description": "Common & Uncommon raw cards. Great for new collectors.",
        "top_pull_text": "D. Pruett Rookie PSA 9 ~$45",
        "rarity_odds": {"Common": 60, "Uncommon": 30, "Rare": 10},
        "cards": [
            ("R. Stallings", "Diamond Kings", "#052", 10, "Common", 13),
            ("M. Iverez", "Diamond Kings", "#061", 9, "Common", 8),
            ("D. Pruett", "Diamond Kings", "#001", 9, "Uncommon", 45),
            ("T. Conklin", "Diamond Kings", "#068", 9, "Uncommon", 22),
            ("B. Mercer", "Rookie Debut", "#034", 9, "Rare", 65),
            ("S. Lindqvist", "Rookie Debut", "#028", 9, "Rare", 90),
        ],
    },
    {
        "category": "Baseball",
        "name": "Silver Raw Card",
        "price": 50,
        "description": "Uncommon & Rare guaranteed. Ultra Rare chance.",
        "top_pull_text": "K. Faraday PSA 10 ~$320",
        "rarity_odds": {"Common": 20, "Uncommon": 40, "Rare": 30, "Ultra Rare": 10},
        "cards": [
            ("A. Brisco", "Diamond Kings", "#057", 9, "Common", 18),
            ("J. Halverson", "Diamond Kings", "#045", 9, "Common", 15),
            ("R. Stallings", "Rookie Debut", "#028", 9, "Uncommon", 40),
            ("B. Mercer", "Rookie Debut", "#060", 9, "Uncommon", 35),
            ("D. Pruett", "Stadium Classics", "#001", 9, "Rare", 266),
            ("M. Iverez", "Stadium Classics", "#008", 9, "Rare", 180),
            ("K. Faraday", "Stadium Classics", "#006", 10, "Ultra Rare", 320),
            ("S. Lindqvist", "Rookie Debut", "#004", 9, "Ultra Rare", 300),
        ],
    },
    {
        "category": "Baseball",
        "name": "Gold Raw Card",
        "price": 100,
        "description": "Rare & Ultra Rare raw cards. Secret Rare 15% chance.",
        "top_pull_text": "T. Conklin PSA 8 ~$1.2k",
        "rarity_odds": {"Uncommon": 10, "Rare": 40, "Ultra Rare": 35, "Secret Rare": 15},
        "cards": [
            ("M. Iverez", "Diamond Kings", "#032", 9, "Uncommon", 55),
            ("J. Halverson", "Diamond Kings", "#009", 9, "Uncommon", 48),
            ("R. Stallings", "Stadium Classics", "#011", 9, "Rare", 210),
            ("A. Brisco", "Stadium Classics", "#010", 9, "Rare", 190),
            ("K. Faraday", "Stadium Classics", "#002", 9, "Ultra Rare", 650),
            ("D. Pruett", "Stadium Classics", "#015", 9, "Ultra Rare", 600),
            ("T. Conklin", "Stadium Classics", "#004", 8, "Secret Rare", 1200),
            ("T. Conklin", "Stadium Classics", "#004", 9, "Secret Rare", 1300),
        ],
    },
    {
        "category": "Baseball",
        "name": "Platinum Raw Card",
        "price": 500,
        "description": "Ultra Rare guaranteed. Trophy & promo raw cards possible.",
        "top_pull_text": "World Series MVP PSA 9 ~$4.8k",
        "rarity_odds": {"Rare": 10, "Ultra Rare": 40, "Secret Rare": 35, "1st Edition": 15},
        "cards": [
            ("D. Pruett", "Diamond Kings", "#010", 9, "Rare", 400),
            ("B. Mercer", "Rookie Debut", "#005", 9, "Rare", 380),
            ("T. Conklin", "Stadium Classics", "#004", 7, "Ultra Rare", 1800),
            ("K. Faraday", "Stadium Classics 1st Ed.", "#002", 8, "Ultra Rare", 2200),
            ("World Series MVP", "Promo", "#TR1", 9, "Secret Rare", 4800),
            ("All-Star Game MVP", "Promo", "#TR2", 9, "Secret Rare", 4500),
            ("T. Conklin", "Stadium Classics 1st Ed.", "#004", 7, "1st Edition", 4900),
            ("K. Faraday", "Stadium Classics 1st Ed.", "#002", 9, "1st Edition", 5000),
        ],
    },
    {
        "category": "Baseball",
        "name": "Diamond Raw Card",
        "price": 1000,
        "description": "Highest tier. 1st Edition pulls highly likely.",
        "top_pull_text": "T. Conklin 1st Ed PSA 10 ~$15k",
        "rarity_odds": {"Ultra Rare": 15, "Secret Rare": 45, "1st Edition": 40},
        "cards": [
            ("T. Conklin", "Stadium Classics", "#004", 9, "Ultra Rare", 6000),
            ("K. Faraday", "Stadium Classics", "#002", 9, "Ultra Rare", 5500),
            ("World Series MVP", "Promo", "#TR1", 10, "Secret Rare", 9000),
            ("Triple Crown Winner", "Promo", "#IL1", 8, "Secret Rare", 8500),
            ("T. Conklin", "Stadium Classics 1st Ed.", "#004", 9, "1st Edition", 12000),
            ("T. Conklin", "Stadium Classics 1st Ed.", "#004", 10, "1st Edition", 15000),
        ],
    },
    {
        "category": "Soccer",
        "name": "Bronze Raw Card",
        "price": 20,
        "description": "Common & Uncommon raw cards. Great for new collectors.",
        "top_pull_text": "M. Eriksson Rookie PSA 9 ~$45",
        "rarity_odds": {"Common": 60, "Uncommon": 30, "Rare": 10},
        "cards": [
            ("K. Olembe", "Pitch Elite", "#052", 10, "Common", 13),
            ("R. Vasquez", "Pitch Elite", "#061", 9, "Common", 8),
            ("M. Eriksson", "Pitch Elite", "#001", 9, "Uncommon", 45),
            ("T. Holloway", "Pitch Elite", "#068", 9, "Uncommon", 22),
            ("J. Castillo", "World Class", "#034", 9, "Rare", 65),
            ("A. Renner", "World Class", "#028", 9, "Rare", 90),
        ],
    },
    {
        "category": "Soccer",
        "name": "Silver Raw Card",
        "price": 50,
        "description": "Uncommon & Rare guaranteed. Ultra Rare chance.",
        "top_pull_text": "S. Okafor PSA 10 ~$320",
        "rarity_odds": {"Common": 20, "Uncommon": 40, "Rare": 30, "Ultra Rare": 10},
        "cards": [
            ("D. Marchetti", "Pitch Elite", "#057", 9, "Common", 18),
            ("K. Olembe", "Pitch Elite", "#045", 9, "Common", 15),
            ("R. Vasquez", "World Class", "#028", 9, "Uncommon", 40),
            ("J. Castillo", "World Class", "#060", 9, "Uncommon", 35),
            ("M. Eriksson", "Golden Boot", "#001", 9, "Rare", 266),
            ("T. Holloway", "Golden Boot", "#008", 9, "Rare", 180),
            ("S. Okafor", "Golden Boot", "#006", 10, "Ultra Rare", 320),
            ("A. Renner", "World Class", "#004", 9, "Ultra Rare", 300),
        ],
    },
    {
        "category": "Soccer",
        "name": "Gold Raw Card",
        "price": 100,
        "description": "Rare & Ultra Rare raw cards. Secret Rare 15% chance.",
        "top_pull_text": "T. Holloway PSA 8 ~$1.2k",
        "rarity_odds": {"Uncommon": 10, "Rare": 40, "Ultra Rare": 35, "Secret Rare": 15},
        "cards": [
            ("R. Vasquez", "Pitch Elite", "#032", 9, "Uncommon", 55),
            ("D. Marchetti", "Pitch Elite", "#009", 9, "Uncommon", 48),
            ("K. Olembe", "Golden Boot", "#011", 9, "Rare", 210),
            ("J. Castillo", "Golden Boot", "#010", 9, "Rare", 190),
            ("S. Okafor", "Golden Boot", "#002", 9, "Ultra Rare", 650),
            ("M. Eriksson", "Golden Boot", "#015", 9, "Ultra Rare", 600),
            ("T. Holloway", "Golden Boot", "#004", 8, "Secret Rare", 1200),
            ("T. Holloway", "Golden Boot", "#004", 9, "Secret Rare", 1300),
        ],
    },
    {
        "category": "Soccer",
        "name": "Platinum Raw Card",
        "price": 500,
        "description": "Ultra Rare guaranteed. Trophy & promo raw cards possible.",
        "top_pull_text": "Ballon d'Or Winner PSA 9 ~$4.8k",
        "rarity_odds": {"Rare": 10, "Ultra Rare": 40, "Secret Rare": 35, "1st Edition": 15},
        "cards": [
            ("M. Eriksson", "Pitch Elite", "#010", 9, "Rare", 400),
            ("J. Castillo", "World Class", "#005", 9, "Rare", 380),
            ("T. Holloway", "Golden Boot", "#004", 7, "Ultra Rare", 1800),
            ("S. Okafor", "Golden Boot 1st Ed.", "#002", 8, "Ultra Rare", 2200),
            ("Ballon d'Or Winner", "Promo", "#TR1", 9, "Secret Rare", 4800),
            ("World Cup MVP", "Promo", "#TR2", 9, "Secret Rare", 4500),
            ("T. Holloway", "Golden Boot 1st Ed.", "#004", 7, "1st Edition", 4900),
            ("S. Okafor", "Golden Boot 1st Ed.", "#002", 9, "1st Edition", 5000),
        ],
    },
    {
        "category": "Soccer",
        "name": "Diamond Raw Card",
        "price": 1000,
        "description": "Highest tier. 1st Edition pulls highly likely.",
        "top_pull_text": "T. Holloway 1st Ed PSA 10 ~$15k",
        "rarity_odds": {"Ultra Rare": 15, "Secret Rare": 45, "1st Edition": 40},
        "cards": [
            ("T. Holloway", "Golden Boot", "#004", 9, "Ultra Rare", 6000),
            ("S. Okafor", "Golden Boot", "#002", 9, "Ultra Rare", 5500),
            ("Ballon d'Or Winner", "Promo", "#TR1", 10, "Secret Rare", 9000),
            ("World Cup Golden Glove", "Promo", "#IL1", 8, "Secret Rare", 8500),
            ("T. Holloway", "Golden Boot 1st Ed.", "#004", 9, "1st Edition", 12000),
            ("T. Holloway", "Golden Boot 1st Ed.", "#004", 10, "1st Edition", 15000),
        ],
    },
    {
        "category": "Women's Soccer",
        "name": "Bronze Raw Card",
        "price": 20,
        "description": "Common & Uncommon raw cards. Great for new collectors.",
        "top_pull_text": "M. Solheim Rookie PSA 9 ~$45",
        "rarity_odds": {"Common": 60, "Uncommon": 30, "Rare": 10},
        "cards": [
            ("K. Fontaine", "Pitch Elite Women", "#052", 10, "Common", 13),
            ("R. Castillo", "Pitch Elite Women", "#061", 9, "Common", 8),
            ("M. Solheim", "Pitch Elite Women", "#001", 9, "Uncommon", 45),
            ("T. Brennan", "Pitch Elite Women", "#068", 9, "Uncommon", 22),
            ("A. Dubois", "World Class Women", "#034", 9, "Rare", 65),
            ("S. Whitfield", "World Class Women", "#028", 9, "Rare", 90),
        ],
    },
    {
        "category": "Women's Soccer",
        "name": "Silver Raw Card",
        "price": 50,
        "description": "Uncommon & Rare guaranteed. Ultra Rare chance.",
        "top_pull_text": "J. Adeyemi PSA 10 ~$320",
        "rarity_odds": {"Common": 20, "Uncommon": 40, "Rare": 30, "Ultra Rare": 10},
        "cards": [
            ("E. Mosley", "Pitch Elite Women", "#057", 9, "Common", 18),
            ("K. Fontaine", "Pitch Elite Women", "#045", 9, "Common", 15),
            ("R. Castillo", "World Class Women", "#028", 9, "Uncommon", 40),
            ("A. Dubois", "World Class Women", "#060", 9, "Uncommon", 35),
            ("M. Solheim", "Golden Boot Women", "#001", 9, "Rare", 266),
            ("T. Brennan", "Golden Boot Women", "#008", 9, "Rare", 180),
            ("J. Adeyemi", "Golden Boot Women", "#006", 10, "Ultra Rare", 320),
            ("S. Whitfield", "World Class Women", "#004", 9, "Ultra Rare", 300),
        ],
    },
    {
        "category": "Women's Soccer",
        "name": "Gold Raw Card",
        "price": 100,
        "description": "Rare & Ultra Rare raw cards. Secret Rare 15% chance.",
        "top_pull_text": "T. Brennan PSA 8 ~$1.2k",
        "rarity_odds": {"Uncommon": 10, "Rare": 40, "Ultra Rare": 35, "Secret Rare": 15},
        "cards": [
            ("R. Castillo", "Pitch Elite Women", "#032", 9, "Uncommon", 55),
            ("E. Mosley", "Pitch Elite Women", "#009", 9, "Uncommon", 48),
            ("K. Fontaine", "Golden Boot Women", "#011", 9, "Rare", 210),
            ("A. Dubois", "Golden Boot Women", "#010", 9, "Rare", 190),
            ("J. Adeyemi", "Golden Boot Women", "#002", 9, "Ultra Rare", 650),
            ("M. Solheim", "Golden Boot Women", "#015", 9, "Ultra Rare", 600),
            ("T. Brennan", "Golden Boot Women", "#004", 8, "Secret Rare", 1200),
            ("T. Brennan", "Golden Boot Women", "#004", 9, "Secret Rare", 1300),
        ],
    },
    {
        "category": "Women's Soccer",
        "name": "Platinum Raw Card",
        "price": 500,
        "description": "Ultra Rare guaranteed. Trophy & promo raw cards possible.",
        "top_pull_text": "Ballon d'Or Femin. Winner PSA 9 ~$4.8k",
        "rarity_odds": {"Rare": 10, "Ultra Rare": 40, "Secret Rare": 35, "1st Edition": 15},
        "cards": [
            ("M. Solheim", "Pitch Elite Women", "#010", 9, "Rare", 400),
            ("A. Dubois", "World Class Women", "#005", 9, "Rare", 380),
            ("T. Brennan", "Golden Boot Women", "#004", 7, "Ultra Rare", 1800),
            ("J. Adeyemi", "Golden Boot Women 1st Ed.", "#002", 8, "Ultra Rare", 2200),
            ("Ballon d'Or Femin. Winner", "Promo", "#TR1", 9, "Secret Rare", 4800),
            ("World Cup MVP", "Promo", "#TR2", 9, "Secret Rare", 4500),
            ("T. Brennan", "Golden Boot Women 1st Ed.", "#004", 7, "1st Edition", 4900),
            ("J. Adeyemi", "Golden Boot Women 1st Ed.", "#002", 9, "1st Edition", 5000),
        ],
    },
    {
        "category": "Women's Soccer",
        "name": "Diamond Raw Card",
        "price": 1000,
        "description": "Highest tier. 1st Edition pulls highly likely.",
        "top_pull_text": "T. Brennan 1st Ed PSA 10 ~$15k",
        "rarity_odds": {"Ultra Rare": 15, "Secret Rare": 45, "1st Edition": 40},
        "cards": [
            ("T. Brennan", "Golden Boot Women", "#004", 9, "Ultra Rare", 6000),
            ("J. Adeyemi", "Golden Boot Women", "#002", 9, "Ultra Rare", 5500),
            ("Ballon d'Or Femin. Winner", "Promo", "#TR1", 10, "Secret Rare", 9000),
            ("World Cup Golden Glove", "Promo", "#IL1", 8, "Secret Rare", 8500),
            ("T. Brennan", "Golden Boot Women 1st Ed.", "#004", 9, "1st Edition", 12000),
            ("T. Brennan", "Golden Boot Women 1st Ed.", "#004", 10, "1st Edition", 15000),
        ],
    },
]


async def seed():
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    async with AsyncSessionLocal() as session:
        for match_data in MATCHES:
            markets = match_data.pop("markets")
            match = Match(**match_data)
            session.add(match)
            await session.flush()  # assigns match.id

            for market_type, data in markets:
                session.add(Market(match_id=match.id, market_type=market_type, data=data))

        for tier_data in PACK_TIERS:
            cards = tier_data.pop("cards")
            tier = PackTier(**tier_data)
            session.add(tier)
            await session.flush()  # assigns tier.id

            for name, set_name, card_number, grade, rarity, market_value in cards:
                session.add(
                    Card(
                        pack_tier_id=tier.id,
                        name=name,
                        set_name=set_name,
                        card_number=card_number,
                        grade=grade,
                        rarity=rarity,
                        market_value=market_value,
                    )
                )

        await session.commit()


if __name__ == "__main__":
    asyncio.run(seed())
